### PR TITLE
generic parttree with partykit/constparty support

### PR DESCRIPTION
**Pull request by zeileis**
Grant, as discussed on Twitter I tried to add support for the `constparty` class from `partykit`:
* Made `parttree()` generic.
* Split up the old non-generic function into methods.
* Add `constparty` method.

Not done:
* Didn't touch the documentation yet, `NAMESPACE`, etc.

Illustrations:

    rp <- rpart(Species ~ Petal.Length + Petal.Width, data = iris)
    parttree(rp)
    rp2 <- as.party(rp)
    parttree(rp2)

Essentially, the two methods give the same output, either via the original `rpart`-based code or via the new `constparty`-based code. Also, this works

    ct <- ctree(Species ~ Petal.Length + Petal.Width, data = iris)
    parttree(ct)

However, for this type of display the midpoint-breaks in `rpart()` are clearly much better than the breaks on the boundary chosen in `ctree()`. This should be improved (at least optionally) in future `partykit` versions.

### CODE REVIEW

**Comment by grantmcdermott** [comment]
This looks fantastic. Thanks Achim!

If you don't mind, please update the documentation (including adding yourself as a contributor) and I'll happily merge.

**Comment by grantmcdermott** [comment]
Something I'm wondering as I write this and having just seen your [tweet](https://twitter.com/AchimZeileis/status/1299478368006660096): Do you think there's value in merging (subsuming) parttree's functionality into the larger partykit or ggparty packages? 

I haven't given this careful consideration, but I'm a fan of users having a one-stop-shop that handles all conceivable use cases...

**Comment by zeileis** [comment]
I hope I've added everything now and didn't overlook anything. I also added a base graphics version to the README.

Regarding putting it into `partykit`: Might be an option but maybe it's a bit specific in its scope. I'll raise it with Heidi and Torsten, though.

**Review by grantmcdermott — APPROVED** [review]
Amazing. Thanks again Achim!

**Pull request merged**
